/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation.rapport;

import entities.Position;
import entities.Vehicule;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import presentation.Main;
import service.PositionService;
import service.VehiculeService;

/**
 *
 * @author HP
 */
public class PositionsRapport extends javax.swing.JFrame {
    private PositionService ps;
    private VehiculeService vs;
    private DefaultTableModel model;
    private static String nom;
    private static String prenom;
    /**
     * Creates new form PositionsRapport
     */
    public PositionsRapport(String nom, String prenom) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.nom = nom;
        this.prenom = prenom;
        ps = new PositionService();
        vs = new VehiculeService();
        model = (DefaultTableModel) listPositions.getModel();
        nameLab.setText(nom + " " + prenom);
        loadVehicules();
    }
    
    private void loadVehicules(){
        for(Vehicule g : vs.findAll())
            vehiculeTxt.addItem(g.getMatricule());      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        exitBtn = new javax.swing.JLabel();
        homeBtn = new javax.swing.JLabel();
        nameLab = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listPositions = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        vehiculeTxt = new javax.swing.JComboBox();
        dateFinTxt = new com.toedter.calendar.JDateChooser();
        dateDebutTxt = new com.toedter.calendar.JDateChooser();
        jPanel7 = new javax.swing.JPanel();
        afficherBtn = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        imprimerBtn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(32, 33, 35));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(51, 102, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(51, 102, 255));
        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 0, 1, 40));

        exitBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentation/images/close.png"))); // NOI18N
        exitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitBtnMouseClicked(evt);
            }
        });
        jPanel3.add(exitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 0, -1, -1));

        homeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentation/images/home.png"))); // NOI18N
        homeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeBtnMouseClicked(evt);
            }
        });
        jPanel3.add(homeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 0, -1, -1));

        nameLab.setFont(new java.awt.Font("Cascadia Mono", 0, 14)); // NOI18N
        jPanel3.add(nameLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 25, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 70));

        jPanel2.setBackground(new java.awt.Color(51, 102, 255));
        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(411, 70, 1, 570));

        jLabel1.setFont(new java.awt.Font("Cascadia Mono", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 102, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Liste des positions");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, 550, -1));

        jLabel2.setFont(new java.awt.Font("Cascadia Mono", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 102, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Formumaire du choix");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 410, -1));

        listPositions.setFont(new java.awt.Font("Cascadia Mono", 0, 12)); // NOI18N
        listPositions.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Tracker", "Date", "Longitude", "Latitude"
            }
        ));
        jScrollPane1.setViewportView(listPositions);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, 510, 480));

        jLabel3.setFont(new java.awt.Font("Cascadia Mono", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 102, 255));
        jLabel3.setText("Véhicule :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 290, -1));

        jLabel4.setFont(new java.awt.Font("Cascadia Mono", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 102, 255));
        jLabel4.setText("Date de début :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 290, -1));

        jLabel5.setFont(new java.awt.Font("Cascadia Mono", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 102, 255));
        jLabel5.setText("Date de fin :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 290, -1));

        vehiculeTxt.setBackground(new java.awt.Color(32, 33, 35));
        vehiculeTxt.setFont(new java.awt.Font("Cascadia Mono", 0, 12)); // NOI18N
        jPanel1.add(vehiculeTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 175, 300, 40));
        jPanel1.add(dateFinTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 375, 290, 35));
        jPanel1.add(dateDebutTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 275, 290, 35));

        jPanel7.setBackground(new java.awt.Color(32, 33, 35));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 255)));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        afficherBtn.setFont(new java.awt.Font("Cascadia Mono", 0, 18)); // NOI18N
        afficherBtn.setForeground(new java.awt.Color(51, 102, 255));
        afficherBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        afficherBtn.setText("AFFICHER");
        afficherBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        afficherBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                afficherBtnMouseClicked(evt);
            }
        });
        jPanel7.add(afficherBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 0, 290, 45));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 480, 290, 45));

        jPanel8.setBackground(new java.awt.Color(32, 33, 35));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 255)));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imprimerBtn.setFont(new java.awt.Font("Cascadia Mono", 0, 18)); // NOI18N
        imprimerBtn.setForeground(new java.awt.Color(51, 102, 255));
        imprimerBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imprimerBtn.setText("IMPRIMER");
        imprimerBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        imprimerBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imprimerBtnMouseClicked(evt);
            }
        });
        jPanel8.add(imprimerBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 45));

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 550, 290, 45));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitBtnMouseClicked

    private void homeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeBtnMouseClicked
        this.setVisible(false);
        (new Main(nom, prenom)).setVisible(true);
    }//GEN-LAST:event_homeBtnMouseClicked

    private void afficherBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_afficherBtnMouseClicked
        Vehicule vehicule = vs.findByMatricule(vehiculeTxt.getSelectedItem().toString());
        Date dateDebut = dateDebutTxt.getDate();
        Date dateFin = dateFinTxt.getDate();
        model.setRowCount(0);
        if(!(dateDebut.equals("") || dateFin.equals(""))){
            List<Position> positions = ps.findPositionsBetweenDates(vehicule, dateDebut, dateFin);
            if(positions.size() > 0){
                for(Position p : positions){
                    model.addRow(new Object []{
                        p.getId(),
                        p.getGpsTracker().getSimNumber(), 
                        p.getDate(),
                        p.getLongitude(),
                        p.getLatitude()                        
                    }); 
                }
            }else
                JOptionPane.showMessageDialog(this, "Aucune position trouvée.");      
        }else
            JOptionPane.showMessageDialog(this, "Tous les champs sont obligatoires.");
    }//GEN-LAST:event_afficherBtnMouseClicked

    private void imprimerBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imprimerBtnMouseClicked
        SimpleDateFormat Date_Format = new SimpleDateFormat("YYYY-MM-dd"); 
        Vehicule vehicule = vs.findByMatricule(vehiculeTxt.getSelectedItem().toString());
        String dateDebut =  Date_Format.format(dateDebutTxt.getDate());
        String dateFin =  Date_Format.format(dateFinTxt.getDate());   
        MessageFormat header = new MessageFormat(vehicule.getMatricule() + " : De "+ dateDebut + " À "  + dateFin);
        MessageFormat footer = new MessageFormat("page {0,number,integer}");
        try {
            listPositions.print(JTable.PrintMode.FIT_WIDTH, header, footer); 
        } catch (Exception e) {
            e.getMessage();
        } 
    }//GEN-LAST:event_imprimerBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PositionsRapport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PositionsRapport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PositionsRapport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PositionsRapport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PositionsRapport(nom, prenom).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel affecterBtn;
    private javax.swing.JLabel affecterBtn1;
    private javax.swing.JLabel afficherBtn;
    private com.toedter.calendar.JDateChooser dateDebutTxt;
    private com.toedter.calendar.JDateChooser dateFinTxt;
    private javax.swing.JLabel exitBtn;
    private javax.swing.JLabel homeBtn;
    private javax.swing.JLabel imprimerBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable listPositions;
    private javax.swing.JLabel nameLab;
    private javax.swing.JComboBox vehiculeTxt;
    // End of variables declaration//GEN-END:variables
}
