/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation.authentification;

import entities.User;
import java.awt.Color;
import javax.swing.JOptionPane;
import presentation.Main;
import service.UserService;
import sécurite.Hash;

/**
 *
 * @author HP
 */
public class Login extends javax.swing.JFrame {
    private UserService us;
    
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        us = new UserService();
        imagePanel.setBackground(new Color(0,0,0,200));
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        loginTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        emailTxt = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        connexionBtn = new javax.swing.JLabel();
        MdpOublieBtn = new javax.swing.JLabel();
        mdpTxt = new javax.swing.JPasswordField();
        exitBtn = new javax.swing.JLabel();
        imagePanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(32, 33, 35));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginTxt.setBackground(new java.awt.Color(32, 33, 35));
        loginTxt.setFont(new java.awt.Font("Cascadia Mono", 0, 12)); // NOI18N
        loginTxt.setForeground(new java.awt.Color(153, 153, 153));
        loginTxt.setBorder(null);
        jPanel1.add(loginTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 270, 30));

        jLabel4.setFont(new java.awt.Font("Cascadia Mono", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 102, 255));
        jLabel4.setText("Nom d'utilisateur :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 270, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 270, 10));

        jLabel5.setFont(new java.awt.Font("Cascadia Mono", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 102, 255));
        jLabel5.setText("Email :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 270, -1));

        emailTxt.setBackground(new java.awt.Color(32, 33, 35));
        emailTxt.setFont(new java.awt.Font("Cascadia Mono", 0, 12)); // NOI18N
        emailTxt.setForeground(new java.awt.Color(153, 153, 153));
        emailTxt.setBorder(null);
        jPanel1.add(emailTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 270, 30));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 270, 10));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, 270, 10));

        jLabel6.setFont(new java.awt.Font("Cascadia Mono", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 102, 255));
        jLabel6.setText("Mot de passe :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 270, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentation/images/userIcone.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 100, 100));

        jLabel8.setFont(new java.awt.Font("Cascadia Mono", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 102, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("CONNEXION");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 100, -1));

        jPanel2.setBackground(new java.awt.Color(32, 33, 35));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 255)));

        connexionBtn.setFont(new java.awt.Font("Cascadia Mono", 0, 18)); // NOI18N
        connexionBtn.setForeground(new java.awt.Color(51, 102, 255));
        connexionBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        connexionBtn.setText("CONNEXION");
        connexionBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        connexionBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                connexionBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(connexionBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(connexionBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 440, 270, 40));

        MdpOublieBtn.setFont(new java.awt.Font("Cascadia Mono", 0, 12)); // NOI18N
        MdpOublieBtn.setForeground(new java.awt.Color(51, 102, 255));
        MdpOublieBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MdpOublieBtn.setText("Mot de passe oublié?");
        MdpOublieBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MdpOublieBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MdpOublieBtnMouseClicked(evt);
            }
        });
        jPanel1.add(MdpOublieBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 520, 270, -1));

        mdpTxt.setBackground(new java.awt.Color(32, 33, 35));
        mdpTxt.setFont(new java.awt.Font("Cascadia Mono", 0, 12)); // NOI18N
        mdpTxt.setForeground(new java.awt.Color(153, 153, 153));
        mdpTxt.setBorder(null);
        jPanel1.add(mdpTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 270, 30));

        exitBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentation/images/close.png"))); // NOI18N
        exitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitBtnMouseClicked(evt);
            }
        });
        jPanel1.add(exitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 40, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 390, 550));

        imagePanel.setBackground(new java.awt.Color(0, 0, 0));
        imagePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Maiandra GD", 1, 55)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 102, 255));
        jLabel2.setText("TRACKER");
        imagePanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, -1, -1));

        jLabel3.setFont(new java.awt.Font("Cascadia Mono", 0, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Application pour suivez les véhicules");
        imagePanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 300, 20));

        getContentPane().add(imagePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 550));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentation/images/loginImageBack.jpg"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(400, 510));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void connexionBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_connexionBtnMouseClicked
        String login = loginTxt.getText();
        String email = emailTxt.getText();
        String password = Hash.encrypt(mdpTxt.getText());
        User user = us.findByLoginAndEmail(login, email);
        if(user != null){
            if(user.getPassword().equals(password)){
                this.setVisible(false);
                (new Main(user.getNom(), user.getPrenom())).setVisible(true);
            }else
                JOptionPane.showMessageDialog(this, "Mot de passe incorrect.");           
        }else
            JOptionPane.showMessageDialog(this, "Nom d'utilisateur ou email incorrect.");       
    }//GEN-LAST:event_connexionBtnMouseClicked

    private void MdpOublieBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MdpOublieBtnMouseClicked
        (new RecupMdp()).setVisible(true); 
    }//GEN-LAST:event_MdpOublieBtnMouseClicked

    private void exitBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MdpOublieBtn;
    private javax.swing.JLabel connexionBtn;
    private javax.swing.JTextField emailTxt;
    private javax.swing.JLabel exitBtn;
    private javax.swing.JPanel imagePanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField loginTxt;
    private javax.swing.JPasswordField mdpTxt;
    // End of variables declaration//GEN-END:variables
}
