/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation.statistics;

import java.awt.BorderLayout;
import java.awt.Color;
import java.text.DecimalFormat;
import java.util.Map;
import javax.swing.JOptionPane;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.labels.PieSectionLabelGenerator;
import org.jfree.chart.labels.StandardPieSectionLabelGenerator;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PiePlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;
import org.jfree.data.general.PieDataset;
import presentation.Main;
import service.PositionService;

/**
 *
 * @author HP
 */
public class PositionsVehicYear extends javax.swing.JFrame {
    private PositionService ps;
    private static String nom;
    private static String prenom;
    private Map<String,Integer> positions;
    private int annee;
    
    /**
     * Creates new form PositionsVehicYear
     */
    public PositionsVehicYear(String nom, String prenom) {
        initComponents();
        ps = new PositionService();
        this.nom = nom;
        this.prenom = prenom;
        this.setLocationRelativeTo(null);
        nameLab.setText(nom + " " + prenom);      
    }

    private void nbrPosVehic1(){
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        for(Map.Entry mp : positions.entrySet())
            dataset.setValue( (Integer)mp.getValue() , "Nombre" , (String)mp.getKey() ); 

        JFreeChart chart = ChartFactory.createBarChart("Nombre des positions par véhicule année " + annee,"Véhicule","Nombre", 
                dataset, PlotOrientation.VERTICAL, false,true,false);

        CategoryPlot categoryPlot = chart.getCategoryPlot();
        categoryPlot.setBackgroundPaint(Color.WHITE);
        BarRenderer renderer = (BarRenderer) categoryPlot.getRenderer();
        Color clr3 = new Color(27,38,44);
        renderer.setSeriesPaint(0, clr3);

        ChartPanel barpChartPanel = new ChartPanel(chart);
        statiticsPanel1.removeAll();
        statiticsPanel1.add(barpChartPanel, BorderLayout.CENTER);
        statiticsPanel1.validate(); 
    }
  
    private void nbrPosVehic2(){
        PieDataset dataset = createDataset();  
        
        JFreeChart chart = ChartFactory.createPieChart("Pourcentage des positions par véhicule année " + annee,  dataset,  false,   true,  false);  
           
        PieSectionLabelGenerator labelGenerator = new StandardPieSectionLabelGenerator(  
            "{0} : ({2})", new DecimalFormat("0"), new DecimalFormat("0.0%")); 
        
        ((PiePlot) chart.getPlot()).setLabelGenerator(labelGenerator);  

        ChartPanel panel = new ChartPanel(chart);  
        
        statiticsPanel2.add(panel, BorderLayout.CENTER);
        statiticsPanel2.validate(); 
    }
    
    private PieDataset createDataset() {  
        DefaultPieDataset dataset=new DefaultPieDataset(); 
        for(Map.Entry mp : positions.entrySet())
            dataset.setValue( (String)mp.getKey(), (Integer)mp.getValue());        
        return dataset;  
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        exitBtn = new javax.swing.JLabel();
        homeBtn = new javax.swing.JLabel();
        nameLab = new javax.swing.JLabel();
        statiticsPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        anneeTxt = new com.toedter.calendar.JYearChooser();
        jPanel5 = new javax.swing.JPanel();
        afficherBtn = new javax.swing.JLabel();
        statiticsPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(32, 33, 35));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(51, 102, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(51, 102, 255));
        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 0, 1, 40));

        exitBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentation/images/close.png"))); // NOI18N
        exitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitBtnMouseClicked(evt);
            }
        });
        jPanel3.add(exitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 0, -1, -1));

        homeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentation/images/home.png"))); // NOI18N
        homeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeBtnMouseClicked(evt);
            }
        });
        jPanel3.add(homeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 0, -1, -1));

        nameLab.setFont(new java.awt.Font("Cascadia Mono", 0, 14)); // NOI18N
        jPanel3.add(nameLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 25, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 70));

        statiticsPanel1.setBackground(new java.awt.Color(255, 255, 255));
        statiticsPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 255)));
        statiticsPanel1.setLayout(new java.awt.BorderLayout());
        jPanel1.add(statiticsPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 450, 420));

        jPanel2.setBackground(new java.awt.Color(51, 102, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 960, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 960, 1));
        jPanel1.add(anneeTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 105, 210, 40));

        jPanel5.setBackground(new java.awt.Color(32, 33, 35));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 255)));

        afficherBtn.setFont(new java.awt.Font("Cascadia Mono", 0, 18)); // NOI18N
        afficherBtn.setForeground(new java.awt.Color(51, 102, 255));
        afficherBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        afficherBtn.setText("AFFICHER");
        afficherBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        afficherBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                afficherBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(afficherBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(afficherBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 105, 180, 40));

        statiticsPanel2.setBackground(new java.awt.Color(255, 255, 255));
        statiticsPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 255)));
        statiticsPanel2.setLayout(new java.awt.BorderLayout());
        jPanel1.add(statiticsPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 200, 450, 420));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitBtnMouseClicked

    private void homeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeBtnMouseClicked
        this.setVisible(false);
        (new Main(nom, prenom)).setVisible(true);
    }//GEN-LAST:event_homeBtnMouseClicked

    private void afficherBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_afficherBtnMouseClicked
        annee = anneeTxt.getValue();
        positions = ps.nbrPositionsByVehiculeYear(annee);
        if(positions.size() > 0){           
            nbrPosVehic1();
            nbrPosVehic2();
        }else
            JOptionPane.showMessageDialog(this, "Aucune position trouvée.");              
    }//GEN-LAST:event_afficherBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PositionsVehicYear.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PositionsVehicYear.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PositionsVehicYear.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PositionsVehicYear.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PositionsVehicYear(nom, prenom).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel afficherBtn;
    private com.toedter.calendar.JYearChooser anneeTxt;
    private javax.swing.JLabel exitBtn;
    private javax.swing.JLabel homeBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel nameLab;
    private javax.swing.JPanel statiticsPanel1;
    private javax.swing.JPanel statiticsPanel2;
    // End of variables declaration//GEN-END:variables
}
