/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation.maps;

import entities.Position;
import entities.Vehicule;
import java.awt.Color;
import java.io.File;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.event.MouseInputListener;
import org.jxmapviewer.OSMTileFactoryInfo;
import org.jxmapviewer.cache.FileBasedLocalCache;
import org.jxmapviewer.input.CenterMapListener;
import org.jxmapviewer.input.PanKeyListener;
import org.jxmapviewer.input.PanMouseInputListener;
import org.jxmapviewer.input.ZoomMouseWheelListenerCenter;
import org.jxmapviewer.viewer.DefaultTileFactory;
import org.jxmapviewer.viewer.GeoPosition;
import org.jxmapviewer.viewer.TileFactoryInfo;
import org.jxmapviewer.viewer.WaypointPainter;
import presentation.Main;
import presentation.maps.classes.FancyWaypointRenderer;
import presentation.maps.classes.MyWaypoint;
import service.PositionService;
import service.VehiculeService;

/**
 *
 * @author HP
 */
public class PosVehicules extends javax.swing.JFrame {
    private VehiculeService vs;
    private PositionService ps;
    private static String nom;
    private static String prenom;
    
    /**
     * Creates new form PosVehicules
     */
    public PosVehicules(String nom, String prenom) {
        initComponents();
        this.nom = nom;
        this.prenom = prenom;
        vs = new VehiculeService();
        ps = new PositionService();
        this.setLocationRelativeTo(null);
        nameLab.setText(nom + " " + prenom);
        loadVehicules();
    }
    
    private void loadVehicules() {
        for(Vehicule v : vs.findAll()) 
            vehiculeTxt.addItem(v.getMatricule()); 
    }
    
    private void loadMap(List<Position> positions) {
        GeoPosition geoPosition[];
        Set<MyWaypoint> waypoints = new HashSet<>();
        List<MyWaypoint> points = new ArrayList();
       
        TileFactoryInfo info = new OSMTileFactoryInfo();
        DefaultTileFactory tileFactory = new DefaultTileFactory(info);

        File cacheDir = new File(System.getProperty("user.home") + File.separator + ".jxmapviewer2");
        tileFactory.setLocalCache(new FileBasedLocalCache(cacheDir, false));

        mapViewer.setTileFactory(tileFactory);

        if(positions.size() > 0){
           geoPosition = new GeoPosition[positions.size()];
           for(int i=0; i<positions.size(); i++)
            geoPosition[i] = new GeoPosition(positions.get(i).getLongitude(),  positions.get(i).getLatitude());   
             
            mapViewer.setZoom(15);
            mapViewer.setAddressLocation(geoPosition[0]);

            MouseInputListener mia = new PanMouseInputListener(mapViewer);
            mapViewer.addMouseListener(mia);
            mapViewer.addMouseMotionListener(mia);
            mapViewer.addMouseListener(new CenterMapListener(mapViewer));
            mapViewer.addMouseWheelListener(new ZoomMouseWheelListenerCenter(mapViewer));
            mapViewer.addKeyListener(new PanKeyListener(mapViewer));

            for(int i=0; i<positions.size(); i++)
                points.add(new MyWaypoint((i+1) +"", Color.RED, geoPosition[i]));
            waypoints = new HashSet<>(points);

            WaypointPainter<MyWaypoint> waypointPainter = new WaypointPainter<>();
            waypointPainter.setWaypoints(waypoints);
            waypointPainter.setRenderer(new FancyWaypointRenderer());
            
            mapViewer.setOverlayPainter(waypointPainter);
            
        }else
            JOptionPane.showMessageDialog(this, "Aucune Position trouvée.");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        exitBtn = new javax.swing.JLabel();
        homeBtn = new javax.swing.JLabel();
        nameLab = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        mapViewer = new org.jxmapviewer.JXMapViewer();
        jLabel3 = new javax.swing.JLabel();
        vehiculeTxt = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        dateDebutTxt = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        dateFinTxt = new com.toedter.calendar.JDateChooser();
        jPanel7 = new javax.swing.JPanel();
        rechercherBtn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(32, 33, 35));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(51, 102, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(51, 102, 255));
        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 0, 1, 40));

        exitBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentation/images/close.png"))); // NOI18N
        exitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitBtnMouseClicked(evt);
            }
        });
        jPanel3.add(exitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 0, -1, -1));

        homeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentation/images/home.png"))); // NOI18N
        homeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeBtnMouseClicked(evt);
            }
        });
        jPanel3.add(homeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 0, -1, -1));

        nameLab.setFont(new java.awt.Font("Cascadia Mono", 0, 14)); // NOI18N
        jPanel3.add(nameLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 25, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 70));

        jPanel2.setBackground(new java.awt.Color(51, 102, 255));
        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, 1, 570));

        javax.swing.GroupLayout mapViewerLayout = new javax.swing.GroupLayout(mapViewer);
        mapViewer.setLayout(mapViewerLayout);
        mapViewerLayout.setHorizontalGroup(
            mapViewerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );
        mapViewerLayout.setVerticalGroup(
            mapViewerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );

        jPanel1.add(mapViewer, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, 570, 570));

        jLabel3.setFont(new java.awt.Font("Cascadia Mono", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 102, 255));
        jLabel3.setText("Véhicule :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 290, -1));

        vehiculeTxt.setBackground(new java.awt.Color(32, 33, 35));
        vehiculeTxt.setFont(new java.awt.Font("Cascadia Mono", 0, 12)); // NOI18N
        jPanel1.add(vehiculeTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 175, 300, 40));

        jLabel4.setFont(new java.awt.Font("Cascadia Mono", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 102, 255));
        jLabel4.setText("Date de début :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 290, -1));
        jPanel1.add(dateDebutTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 275, 290, 35));

        jLabel5.setFont(new java.awt.Font("Cascadia Mono", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 102, 255));
        jLabel5.setText("Date de fin :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 290, -1));
        jPanel1.add(dateFinTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 375, 290, 35));

        jPanel7.setBackground(new java.awt.Color(32, 33, 35));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 255)));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rechercherBtn.setFont(new java.awt.Font("Cascadia Mono", 0, 18)); // NOI18N
        rechercherBtn.setForeground(new java.awt.Color(51, 102, 255));
        rechercherBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rechercherBtn.setText("RECHERCHER");
        rechercherBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rechercherBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rechercherBtnMouseClicked(evt);
            }
        });
        jPanel7.add(rechercherBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 0, 290, 45));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 480, 290, 45));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitBtnMouseClicked

    private void homeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeBtnMouseClicked
        this.setVisible(false);
        (new Main(nom, prenom)).setVisible(true);
    }//GEN-LAST:event_homeBtnMouseClicked

    private void rechercherBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rechercherBtnMouseClicked
        Vehicule vehicule = vs.findByMatricule(vehiculeTxt.getSelectedItem().toString());
        Date dateD = dateDebutTxt.getDate();
        Date dateF = dateFinTxt.getDate();
        if(!(dateD.equals("") || dateF.equals(""))){
            List<Position> positions = ps.findPositionsBetweenDates(vehicule, dateD, dateF);
            loadMap(positions);
        }else
            JOptionPane.showMessageDialog(this, "Tous les champs sont obligatoires.");
    }//GEN-LAST:event_rechercherBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PosVehicules.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PosVehicules.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PosVehicules.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PosVehicules.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PosVehicules(nom, prenom).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser dateDebutTxt;
    private com.toedter.calendar.JDateChooser dateFinTxt;
    private javax.swing.JLabel exitBtn;
    private javax.swing.JLabel homeBtn;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private org.jxmapviewer.JXMapViewer mapViewer;
    private javax.swing.JLabel nameLab;
    private javax.swing.JLabel rechercherBtn;
    private javax.swing.JComboBox vehiculeTxt;
    // End of variables declaration//GEN-END:variables
}
