/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation.gestion;

import entities.Vehicule;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import presentation.Main;
import service.VehiculeService;

/**
 *
 * @author HP
 */
public class GestionVehicules extends javax.swing.JFrame {
    private VehiculeService vs;
    private DefaultTableModel model;
    private static int id;
    private static String nom;
    private static String prenom;
    
    /**
     * Creates new form GestionVehicules
     */
    public GestionVehicules(String nom, String prenom) {
        initComponents();
        this.nom = nom;
        this.prenom = prenom;
        this.setLocationRelativeTo(null);
        vs = new VehiculeService();
        model = (DefaultTableModel) listVehicules.getModel();
        nameLab.setText(nom + " " + prenom);
        load();
    }

    private void load(){
        model.setRowCount(0);
        for(Vehicule v : vs.findAll()){
            model.addRow(new Object []{
                v.getId(),
                v.getMatricule(),
                v.getMarque(),
                v.getType()
            });
        }
    }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        exitBtn = new javax.swing.JLabel();
        homeBtn = new javax.swing.JLabel();
        nameLab = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listVehicules = new javax.swing.JTable();
        matriculeTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        typeTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        deleteBtn = new javax.swing.JLabel();
        addBtn = new javax.swing.JLabel();
        updateBtn = new javax.swing.JLabel();
        marqueTxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(32, 33, 35));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(51, 102, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(51, 102, 255));
        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 0, 1, 40));

        exitBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentation/images/close.png"))); // NOI18N
        exitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitBtnMouseClicked(evt);
            }
        });
        jPanel3.add(exitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 0, -1, -1));

        homeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentation/images/home.png"))); // NOI18N
        homeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeBtnMouseClicked(evt);
            }
        });
        jPanel3.add(homeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 0, -1, -1));

        nameLab.setFont(new java.awt.Font("Cascadia Mono", 0, 14)); // NOI18N
        jPanel3.add(nameLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 25, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 70));

        jPanel2.setBackground(new java.awt.Color(51, 102, 255));
        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(411, 70, 1, 570));

        jLabel1.setFont(new java.awt.Font("Cascadia Mono", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 102, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Liste des véhicules");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, 550, -1));

        jLabel2.setFont(new java.awt.Font("Cascadia Mono", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 102, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Formumaire de gestion");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 410, -1));

        listVehicules.setFont(new java.awt.Font("Cascadia Mono", 0, 12)); // NOI18N
        listVehicules.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Matricule", "Marque", "Type"
            }
        ));
        listVehicules.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listVehiculesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listVehicules);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, 510, 480));

        matriculeTxt.setBackground(new java.awt.Color(32, 33, 35));
        matriculeTxt.setFont(new java.awt.Font("Cascadia Mono", 0, 12)); // NOI18N
        matriculeTxt.setForeground(new java.awt.Color(153, 153, 153));
        matriculeTxt.setBorder(null);
        jPanel1.add(matriculeTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 290, 30));

        jLabel3.setFont(new java.awt.Font("Cascadia Mono", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 102, 255));
        jLabel3.setText("Matricule :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 290, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 290, 10));

        typeTxt.setBackground(new java.awt.Color(32, 33, 35));
        typeTxt.setFont(new java.awt.Font("Cascadia Mono", 0, 12)); // NOI18N
        typeTxt.setForeground(new java.awt.Color(153, 153, 153));
        typeTxt.setBorder(null);
        jPanel1.add(typeTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, 290, 30));

        jLabel5.setFont(new java.awt.Font("Cascadia Mono", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 102, 255));
        jLabel5.setText("Marque :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 290, -1));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 290, 10));

        jLabel7.setFont(new java.awt.Font("Cascadia Mono", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 102, 255));
        jLabel7.setText("Type :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, 290, -1));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 440, 290, 10));

        deleteBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentation/images/delete.png"))); // NOI18N
        deleteBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteBtnMouseClicked(evt);
            }
        });
        jPanel1.add(deleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 500, 45, 45));

        addBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentation/images/add.png"))); // NOI18N
        addBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addBtnMouseClicked(evt);
            }
        });
        jPanel1.add(addBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 500, 45, 45));

        updateBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentation/images/refresh.png"))); // NOI18N
        updateBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updateBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateBtnMouseClicked(evt);
            }
        });
        jPanel1.add(updateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 500, 45, 45));

        marqueTxt.setBackground(new java.awt.Color(32, 33, 35));
        marqueTxt.setFont(new java.awt.Font("Cascadia Mono", 0, 12)); // NOI18N
        marqueTxt.setForeground(new java.awt.Color(153, 153, 153));
        marqueTxt.setBorder(null);
        jPanel1.add(marqueTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 290, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitBtnMouseClicked

    private void homeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeBtnMouseClicked
        this.setVisible(false);
        (new Main(nom, prenom)).setVisible(true);
    }//GEN-LAST:event_homeBtnMouseClicked

    private void listVehiculesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listVehiculesMouseClicked
        id = Integer.parseInt(model.getValueAt(listVehicules.getSelectedRow(), 0).toString());
        matriculeTxt.setText(model.getValueAt(listVehicules.getSelectedRow(), 1).toString());
        typeTxt.setText(model.getValueAt(listVehicules.getSelectedRow(), 2).toString());
        typeTxt.setText(model.getValueAt(listVehicules.getSelectedRow(), 3).toString());
    }//GEN-LAST:event_listVehiculesMouseClicked

    private void deleteBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteBtnMouseClicked
        if(id != 0){
            int choix = JOptionPane.showConfirmDialog(this, "Vous étes sur?");
            if(choix == 0){
                if(vs.delete(vs.findById(id))){
                    matriculeTxt.setText("");
                    marqueTxt.setText("");
                    typeTxt.setText("");
                    id = 0;
                    load();
                }else{
                    JOptionPane.showMessageDialog(this, "Impossible de supprimer cette véhicule.");
                    matriculeTxt.setText("");
                    marqueTxt.setText("");
                    typeTxt.setText("");
                }                  
            }
        }else
            JOptionPane.showMessageDialog(this, "Veuillez choisir une véhicule.");
    }//GEN-LAST:event_deleteBtnMouseClicked

    private void addBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addBtnMouseClicked
        String matricule = matriculeTxt.getText();
        String type = typeTxt.getText();
        String marque = typeTxt.getText();
        if(!(matricule.equals("") || type.equals("") || marque.equals(""))){
            if(vs.create(new Vehicule(matricule, marque, type)))
                load();
            else
                JOptionPane.showMessageDialog(this, "Véhicule existe déja.");
        }else
            JOptionPane.showMessageDialog(this, "Tous les champs sont obligatoires.");
    }//GEN-LAST:event_addBtnMouseClicked

    private void updateBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateBtnMouseClicked
        if(id != 0){
            int choix = JOptionPane.showConfirmDialog(this, "Vous étes sur?");
            String matricule = matriculeTxt.getText();
            String type = typeTxt.getText();
            String marque = typeTxt.getText();
            Vehicule vehicule = vs.findById(id);
            vehicule.setMatricule(matricule);
            vehicule.setType(type);
            vehicule.setMarque(marque);
            if(choix == 0){
                if(vs.update(vehicule)){
                    matriculeTxt.setText("");
                    typeTxt.setText("");
                    typeTxt.setText("");
                    id = 0;
                    load();
                }
            }
        }else
            JOptionPane.showMessageDialog(this, "Aucune véhicule choisi.");
    }//GEN-LAST:event_updateBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionVehicules.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionVehicules.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionVehicules.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionVehicules.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionVehicules(nom, prenom).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addBtn;
    private javax.swing.JLabel deleteBtn;
    private javax.swing.JLabel exitBtn;
    private javax.swing.JLabel homeBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTable listVehicules;
    private javax.swing.JTextField marqueTxt;
    private javax.swing.JTextField matriculeTxt;
    private javax.swing.JLabel nameLab;
    private javax.swing.JTextField typeTxt;
    private javax.swing.JLabel updateBtn;
    // End of variables declaration//GEN-END:variables
}
