/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation.gestion;

import entities.GPSTracker;
import entities.Position;
import entities.VehiculeGPSTracker;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import presentation.Main;
import service.GPSTrackerService;
import service.PositionService;
import service.VehiculeGPSTrackerService;

/**
 *
 * @author HP
 */
public class GestionPositions extends javax.swing.JFrame {
    private PositionService ps;
    private VehiculeGPSTrackerService vgs;
    private GPSTrackerService gs;
    private DefaultTableModel model;
    private static int id;
    private static String nom;
    private static String prenom;
    
    /**
     * Creates new form GestionPositions
     */
    public GestionPositions(String nom, String prenom) {
        initComponents();
        this.nom = nom;
        this.prenom = prenom;
        this.setLocationRelativeTo(null);
        ps = new PositionService();
        vgs = new VehiculeGPSTrackerService();
        gs = new GPSTrackerService();
        model = (DefaultTableModel) listPositions.getModel();
        nameLab.setText(nom + " " + prenom);
        load();
        loadTrackers();
    }

    private void load() {
        model.setRowCount(0);
        for(Position p : ps.findAll()){
            model.addRow(new Object []{
                p.getId(),
                p.getGpsTracker().getSimNumber(),
                p.getDate(),
                p.getLongitude(),
                p.getLatitude()
            });
        }    
    }
    
    private void loadTrackers(){
        for(GPSTracker g : vgs.findTrackersNull())
            trackerTxt.addItem(g.getSimNumber());      
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        exitBtn = new javax.swing.JLabel();
        homeBtn = new javax.swing.JLabel();
        nameLab = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listPositions = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        longitudeTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        latitudeTxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        deleteBtn = new javax.swing.JLabel();
        addBtn = new javax.swing.JLabel();
        updateBtn = new javax.swing.JLabel();
        trackerTxt = new javax.swing.JComboBox();
        dateTxt = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(32, 33, 35));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(51, 102, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(51, 102, 255));
        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 0, 1, 40));

        exitBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentation/images/close.png"))); // NOI18N
        exitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitBtnMouseClicked(evt);
            }
        });
        jPanel3.add(exitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 0, -1, -1));

        homeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentation/images/home.png"))); // NOI18N
        homeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeBtnMouseClicked(evt);
            }
        });
        jPanel3.add(homeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 0, -1, -1));

        nameLab.setFont(new java.awt.Font("Cascadia Mono", 0, 14)); // NOI18N
        jPanel3.add(nameLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 25, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 70));

        jPanel2.setBackground(new java.awt.Color(51, 102, 255));
        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(411, 70, 1, 570));

        jLabel1.setFont(new java.awt.Font("Cascadia Mono", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 102, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Liste des positions");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, 550, -1));

        jLabel2.setFont(new java.awt.Font("Cascadia Mono", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 102, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Formumaire de gestion");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 410, -1));

        listPositions.setFont(new java.awt.Font("Cascadia Mono", 0, 12)); // NOI18N
        listPositions.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Tracker", "Date", "Longitude", "Latitude"
            }
        ));
        listPositions.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listPositionsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listPositions);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, 510, 480));

        jLabel3.setFont(new java.awt.Font("Cascadia Mono", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 102, 255));
        jLabel3.setText("Tracker :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 290, -1));

        jLabel4.setFont(new java.awt.Font("Cascadia Mono", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 102, 255));
        jLabel4.setText("Date de position :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 290, -1));

        longitudeTxt.setBackground(new java.awt.Color(32, 33, 35));
        longitudeTxt.setFont(new java.awt.Font("Cascadia Mono", 0, 12)); // NOI18N
        longitudeTxt.setForeground(new java.awt.Color(153, 153, 153));
        longitudeTxt.setBorder(null);
        jPanel1.add(longitudeTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 290, 30));

        jLabel5.setFont(new java.awt.Font("Cascadia Mono", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 102, 255));
        jLabel5.setText("Longitude :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 290, -1));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, 290, 10));

        latitudeTxt.setBackground(new java.awt.Color(32, 33, 35));
        latitudeTxt.setFont(new java.awt.Font("Cascadia Mono", 0, 12)); // NOI18N
        latitudeTxt.setForeground(new java.awt.Color(153, 153, 153));
        latitudeTxt.setBorder(null);
        jPanel1.add(latitudeTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 460, 290, 30));

        jLabel6.setFont(new java.awt.Font("Cascadia Mono", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 102, 255));
        jLabel6.setText("Latitude :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 440, 290, -1));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 490, 290, 10));

        deleteBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentation/images/delete.png"))); // NOI18N
        deleteBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteBtnMouseClicked(evt);
            }
        });
        jPanel1.add(deleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 540, 45, 45));

        addBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentation/images/add.png"))); // NOI18N
        addBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addBtnMouseClicked(evt);
            }
        });
        jPanel1.add(addBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 540, 45, 45));

        updateBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentation/images/refresh.png"))); // NOI18N
        updateBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updateBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateBtnMouseClicked(evt);
            }
        });
        jPanel1.add(updateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 540, 45, 45));

        trackerTxt.setBackground(new java.awt.Color(32, 33, 35));
        trackerTxt.setFont(new java.awt.Font("Cascadia Mono", 0, 12)); // NOI18N
        jPanel1.add(trackerTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 175, 300, 40));
        jPanel1.add(dateTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 275, 290, 35));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitBtnMouseClicked

    private void homeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeBtnMouseClicked
        this.setVisible(false);
        (new Main(nom, prenom)).setVisible(true);
    }//GEN-LAST:event_homeBtnMouseClicked

    private void listPositionsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listPositionsMouseClicked
        id = Integer.parseInt(model.getValueAt(listPositions.getSelectedRow(), 0).toString());
        boolean verification = false;
        GPSTracker g = gs.findBySimNumber(model.getValueAt(listPositions.getSelectedRow(), 1).toString());
        
        for(VehiculeGPSTracker vg : vgs.findByTrackerId(g.getId())){    
            if(vg.getDateFin() != null)
                verification = true;
            else
                verification = false;
        }
        
        if(verification){
            JOptionPane.showMessageDialog(this, "Impossible de modifier ou supprimer cette position.");
            id = 0;
        }
        else{
            dateTxt.setDate((Date) model.getValueAt(listPositions.getSelectedRow(), 2));
            longitudeTxt.setText(model.getValueAt(listPositions.getSelectedRow(), 3).toString());
            latitudeTxt.setText(model.getValueAt(listPositions.getSelectedRow(), 4).toString());
        }
    }//GEN-LAST:event_listPositionsMouseClicked

    private void deleteBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteBtnMouseClicked
        if(id != 0){
            int choix = JOptionPane.showConfirmDialog(this, "Vous étes sur?");
            if(choix == 0){
                if(ps.delete(ps.findById(id))){
                    longitudeTxt.setText("Longitude");
                    latitudeTxt.setText("Latitude");
                    id = 0;
                    load();
                }else{
                    JOptionPane.showMessageDialog(this, "Impossible de supprimer cette position.");
                    longitudeTxt.setText("");
                    latitudeTxt.setText("");
                }
            }
        }else
            JOptionPane.showMessageDialog(this, "Aucun position choisi!!!");
    }//GEN-LAST:event_deleteBtnMouseClicked

    private void addBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addBtnMouseClicked
        GPSTracker tracker = gs.findBySimNumber(trackerTxt.getSelectedItem().toString()) ;
        Date date = dateTxt.getDate();
        String longitude = longitudeTxt.getText();
        String latitude = latitudeTxt.getText();
        if(!(date.equals("") || longitude.equals("") || latitude.equals(""))){
            if(ps.create(new Position(Double.parseDouble(latitude), Double.parseDouble(longitude), date, tracker)))
                load();
            else
                JOptionPane.showMessageDialog(this, "Date choisie incorrect.");
        }else
            JOptionPane.showMessageDialog(this, "Tous les champs sont obligatoires.");
    }//GEN-LAST:event_addBtnMouseClicked

    private void updateBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateBtnMouseClicked
        if(id != 0){
            int choix = JOptionPane.showConfirmDialog(this, "Vous étes sur?");
            GPSTracker tracker = gs.findBySimNumber(trackerTxt.getSelectedItem().toString()) ;
            Date date = dateTxt.getDate();
            String longitude = longitudeTxt.getText();
            String latitude = latitudeTxt.getText();
            Position position = ps.findById(id);
            position.setDate(date);
            position.setLongitude(Double.parseDouble(longitude));
            position.setLatitude(Double.parseDouble(latitude));
            position.setGpsTracker(tracker);
            if(choix == 0){
                if(ps.update(position)){
                    longitudeTxt.setText("");
                    latitudeTxt.setText("");
                    id = 0;
                    load();
                }
            }
        }else
            JOptionPane.showMessageDialog(this, "Veuillez choisir une position.");
    }//GEN-LAST:event_updateBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionPositions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionPositions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionPositions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionPositions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionPositions(nom,prenom).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addBtn;
    private com.toedter.calendar.JDateChooser dateTxt;
    private javax.swing.JLabel deleteBtn;
    private javax.swing.JLabel exitBtn;
    private javax.swing.JLabel homeBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField latitudeTxt;
    private javax.swing.JTable listPositions;
    private javax.swing.JTextField longitudeTxt;
    private javax.swing.JLabel nameLab;
    private javax.swing.JComboBox trackerTxt;
    private javax.swing.JLabel updateBtn;
    // End of variables declaration//GEN-END:variables
}
