/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation.gestion;

import entities.GPSTracker;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import presentation.Main;
import service.GPSTrackerService;

/**
 *
 * @author HP
 */
public class GestionTrackers extends javax.swing.JFrame {
    private GPSTrackerService gs;
    private DefaultTableModel model;
    private static int id;
    private static String nom;
    private static String prenom;
    
    /**
     * Creates new form GestionTrackers
     */
    public GestionTrackers(String nom, String prenom) {
        initComponents();
        this.nom = nom;
        this.prenom = prenom;
        gs = new GPSTrackerService();
        this.setLocationRelativeTo(null);
        model = (DefaultTableModel) listeTrackers.getModel();
        nameLab.setText(nom + " " + prenom);
        load();
    }
    
    private void load(){
        model.setRowCount(0);
        for(GPSTracker g : gs.findAll()){
            model.addRow(new Object []{
                g.getId(),
                g.getSimNumber()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        exitBtn = new javax.swing.JLabel();
        homeBtn = new javax.swing.JLabel();
        nameLab = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        simNumberTxt = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        addBtn = new javax.swing.JLabel();
        updateBtn = new javax.swing.JLabel();
        deleteBtn = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listeTrackers = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(32, 33, 35));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 102, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(51, 102, 255));
        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 0, 1, 40));

        exitBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentation/images/close.png"))); // NOI18N
        exitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitBtnMouseClicked(evt);
            }
        });
        jPanel2.add(exitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 0, -1, -1));

        homeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentation/images/home.png"))); // NOI18N
        homeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeBtnMouseClicked(evt);
            }
        });
        jPanel2.add(homeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 0, -1, -1));

        nameLab.setFont(new java.awt.Font("Cascadia Mono", 0, 14)); // NOI18N
        jPanel2.add(nameLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 25, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 70));

        jPanel3.setBackground(new java.awt.Color(51, 102, 255));
        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, 1, 420));

        jLabel2.setFont(new java.awt.Font("Cascadia Mono", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 102, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Formumaire de gestion");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 320, -1));

        jLabel1.setFont(new java.awt.Font("Cascadia Mono", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 102, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Liste des trackers");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 410, -1));

        jLabel3.setFont(new java.awt.Font("Cascadia Mono", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 102, 255));
        jLabel3.setText("Sim number :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 260, -1));

        simNumberTxt.setBackground(new java.awt.Color(32, 33, 35));
        simNumberTxt.setFont(new java.awt.Font("Cascadia Mono", 0, 12)); // NOI18N
        simNumberTxt.setForeground(new java.awt.Color(153, 153, 153));
        simNumberTxt.setBorder(null);
        jPanel1.add(simNumberTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 260, 30));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 260, 10));

        addBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentation/images/add.png"))); // NOI18N
        addBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addBtnMouseClicked(evt);
            }
        });
        jPanel1.add(addBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 45, 45));

        updateBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentation/images/refresh.png"))); // NOI18N
        updateBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updateBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateBtnMouseClicked(evt);
            }
        });
        jPanel1.add(updateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 45, 45));

        deleteBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentation/images/delete.png"))); // NOI18N
        deleteBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteBtnMouseClicked(evt);
            }
        });
        jPanel1.add(deleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 390, 45, 45));

        listeTrackers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Sim number"
            }
        ));
        listeTrackers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listeTrackersMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listeTrackers);
        if (listeTrackers.getColumnModel().getColumnCount() > 0) {
            listeTrackers.getColumnModel().getColumn(0).setMinWidth(125);
            listeTrackers.getColumnModel().getColumn(0).setPreferredWidth(125);
            listeTrackers.getColumnModel().getColumn(0).setMaxWidth(125);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, 320, 340));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitBtnMouseClicked

    private void homeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeBtnMouseClicked
        this.setVisible(false);
        (new Main(nom, prenom)).setVisible(true);
    }//GEN-LAST:event_homeBtnMouseClicked

    private void addBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addBtnMouseClicked
        String simNumber = simNumberTxt.getText();
        if(!simNumber.equals("")){
            if(gs.create(new GPSTracker(simNumber))){
                load();   
                simNumberTxt.setText("");
            }
            else
                JOptionPane.showMessageDialog(this, "Tracker existe déja.");
        }else
            JOptionPane.showMessageDialog(this, "Tous les champs sont obligatoires.");
    }//GEN-LAST:event_addBtnMouseClicked

    private void updateBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateBtnMouseClicked
        if(id != 0){
            int choix = JOptionPane.showConfirmDialog(this, "Vous étes sur?");
            String simNumberT = simNumberTxt.getText();
            GPSTracker gPSTracker = gs.findById(id);
            gPSTracker.setSimNumber(simNumberT);
            if(choix == 0){
                if(gs.update(gPSTracker)){
                    simNumberTxt.setText("");
                    id = 0;
                    load();
                }
            }
        }else
            JOptionPane.showMessageDialog(this, "Veuillez choisir un tracker.");
    }//GEN-LAST:event_updateBtnMouseClicked

    private void deleteBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteBtnMouseClicked
        if(id != 0){
            int choix = JOptionPane.showConfirmDialog(this, "Vous étes sur?");
            if(choix == 0){
                if(gs.delete(gs.findById(id))){
                    simNumberTxt.setText("");
                    id = 0;
                    load();
                }else
                    JOptionPane.showMessageDialog(this, "Impossible de supprimer ce tracker.");
            }
        }else
            JOptionPane.showMessageDialog(this, "Veuillez choisir un tracker.");
    }//GEN-LAST:event_deleteBtnMouseClicked

    private void listeTrackersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listeTrackersMouseClicked
        id = Integer.parseInt(model.getValueAt(listeTrackers.getSelectedRow(), 0).toString());
        simNumberTxt.setText(model.getValueAt(listeTrackers.getSelectedRow(), 1).toString());
    }//GEN-LAST:event_listeTrackersMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionTrackers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionTrackers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionTrackers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionTrackers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionTrackers(nom, prenom).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addBtn;
    private javax.swing.JLabel deleteBtn;
    private javax.swing.JLabel exitBtn;
    private javax.swing.JLabel homeBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable listeTrackers;
    private javax.swing.JLabel nameLab;
    private javax.swing.JTextField simNumberTxt;
    private javax.swing.JLabel updateBtn;
    // End of variables declaration//GEN-END:variables
}
