/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation.gestion;

import entities.User;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import presentation.Main;
import service.UserService;
import sécurite.Hash;

/**
 *
 * @author HP
 */
public class GestionUsers extends javax.swing.JFrame {
    private UserService us;
    private DefaultTableModel model;
    private static int id;
    private static String nom;
    private static String prenom;
    
    /**
     * Creates new form GestionUsers
     */
    public GestionUsers(String nom, String prenom) {
        initComponents();
        this.nom = nom;
        this.prenom = prenom;
        this.setLocationRelativeTo(null);
        us = new UserService();
        model = (DefaultTableModel) listUsers.getModel();
        nameLab.setText(nom + " " + prenom);
        load();
    }
    
    private void load() {
        model.setRowCount(0);
        for(User u : us.findAll()){
            model.addRow(new Object []{
                u.getId(),
                u.getNom(),
                u.getPrenom(),
                u.getLogin(),
                u.getEmail()
            });
        }    
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        exitBtn = new javax.swing.JLabel();
        homeBtn = new javax.swing.JLabel();
        nameLab = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listUsers = new javax.swing.JTable();
        nomTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        prenomTxt = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        loginTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        emailTxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        mdpTxt = new javax.swing.JPasswordField();
        deleteBtn = new javax.swing.JLabel();
        addBtn = new javax.swing.JLabel();
        updateBtn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(32, 33, 35));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(51, 102, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(51, 102, 255));
        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 0, 1, 40));

        exitBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentation/images/close.png"))); // NOI18N
        exitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitBtnMouseClicked(evt);
            }
        });
        jPanel3.add(exitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 0, -1, -1));

        homeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentation/images/home.png"))); // NOI18N
        homeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeBtnMouseClicked(evt);
            }
        });
        jPanel3.add(homeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 0, -1, -1));

        nameLab.setFont(new java.awt.Font("Cascadia Mono", 0, 14)); // NOI18N
        jPanel3.add(nameLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 25, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 70));

        jPanel2.setBackground(new java.awt.Color(51, 102, 255));
        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(411, 70, 1, 570));

        jLabel1.setFont(new java.awt.Font("Cascadia Mono", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 102, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Liste des utilisateurs");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, 550, -1));

        jLabel2.setFont(new java.awt.Font("Cascadia Mono", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 102, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Formumaire de gestion");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 410, -1));

        listUsers.setFont(new java.awt.Font("Cascadia Mono", 0, 12)); // NOI18N
        listUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nom", "Prénom", "Nom d'utilisateur", "Email"
            }
        ));
        listUsers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listUsersMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listUsers);
        if (listUsers.getColumnModel().getColumnCount() > 0) {
            listUsers.getColumnModel().getColumn(0).setMinWidth(40);
            listUsers.getColumnModel().getColumn(0).setPreferredWidth(40);
            listUsers.getColumnModel().getColumn(0).setMaxWidth(40);
            listUsers.getColumnModel().getColumn(1).setMinWidth(80);
            listUsers.getColumnModel().getColumn(1).setPreferredWidth(80);
            listUsers.getColumnModel().getColumn(1).setMaxWidth(80);
            listUsers.getColumnModel().getColumn(2).setMinWidth(80);
            listUsers.getColumnModel().getColumn(2).setPreferredWidth(80);
            listUsers.getColumnModel().getColumn(2).setMaxWidth(80);
            listUsers.getColumnModel().getColumn(3).setMinWidth(110);
            listUsers.getColumnModel().getColumn(3).setPreferredWidth(110);
            listUsers.getColumnModel().getColumn(3).setMaxWidth(110);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, 510, 480));

        nomTxt.setBackground(new java.awt.Color(32, 33, 35));
        nomTxt.setFont(new java.awt.Font("Cascadia Mono", 0, 12)); // NOI18N
        nomTxt.setForeground(new java.awt.Color(153, 153, 153));
        nomTxt.setBorder(null);
        jPanel1.add(nomTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 290, 30));

        jLabel3.setFont(new java.awt.Font("Cascadia Mono", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 102, 255));
        jLabel3.setText("Nom :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 290, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 290, 10));

        jLabel4.setFont(new java.awt.Font("Cascadia Mono", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 102, 255));
        jLabel4.setText("Prénom :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 290, -1));

        prenomTxt.setBackground(new java.awt.Color(32, 33, 35));
        prenomTxt.setFont(new java.awt.Font("Cascadia Mono", 0, 12)); // NOI18N
        prenomTxt.setForeground(new java.awt.Color(153, 153, 153));
        prenomTxt.setBorder(null);
        jPanel1.add(prenomTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 290, 30));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 290, 10));

        loginTxt.setBackground(new java.awt.Color(32, 33, 35));
        loginTxt.setFont(new java.awt.Font("Cascadia Mono", 0, 12)); // NOI18N
        loginTxt.setForeground(new java.awt.Color(153, 153, 153));
        loginTxt.setBorder(null);
        jPanel1.add(loginTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 290, 30));

        jLabel5.setFont(new java.awt.Font("Cascadia Mono", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 102, 255));
        jLabel5.setText("Nom d'utilisateur :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 290, -1));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 290, 10));

        emailTxt.setBackground(new java.awt.Color(32, 33, 35));
        emailTxt.setFont(new java.awt.Font("Cascadia Mono", 0, 12)); // NOI18N
        emailTxt.setForeground(new java.awt.Color(153, 153, 153));
        emailTxt.setBorder(null);
        jPanel1.add(emailTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, 290, 30));

        jLabel6.setFont(new java.awt.Font("Cascadia Mono", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 102, 255));
        jLabel6.setText("Email :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, 290, -1));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 440, 290, 10));

        jLabel7.setFont(new java.awt.Font("Cascadia Mono", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 102, 255));
        jLabel7.setText("mot de passe :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 470, 290, -1));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 520, 290, 10));

        mdpTxt.setBackground(new java.awt.Color(32, 33, 35));
        mdpTxt.setFont(new java.awt.Font("Cascadia Mono", 0, 12)); // NOI18N
        mdpTxt.setForeground(new java.awt.Color(153, 153, 153));
        mdpTxt.setBorder(null);
        jPanel1.add(mdpTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 490, 290, 30));

        deleteBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentation/images/delete.png"))); // NOI18N
        deleteBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteBtnMouseClicked(evt);
            }
        });
        jPanel1.add(deleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 560, 45, 45));

        addBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentation/images/add.png"))); // NOI18N
        addBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addBtnMouseClicked(evt);
            }
        });
        jPanel1.add(addBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 560, 45, 45));

        updateBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentation/images/refresh.png"))); // NOI18N
        updateBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updateBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateBtnMouseClicked(evt);
            }
        });
        jPanel1.add(updateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 560, 45, 45));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeBtnMouseClicked
        this.setVisible(false);
        (new Main(nom, prenom)).setVisible(true);
    }//GEN-LAST:event_homeBtnMouseClicked

    private void exitBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitBtnMouseClicked

    private void addBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addBtnMouseClicked
        String nom = nomTxt.getText();
        String prenom = prenomTxt.getText();
        String login = loginTxt.getText();
        String email = emailTxt.getText();
        String password = Hash.encrypt(mdpTxt.getText());
        if(!(nom.equals("") || prenom.equals("") || login.equals("") || email.equals("") || password.equals(""))){
            if(us.create(new User(nom, prenom, login, email, password)))
                load();
            else
                JOptionPane.showMessageDialog(this, "Utilisateur existe déja.");
            
        }else
            JOptionPane.showMessageDialog(this, "Tous les champs sont obligatoires.");
        
    }//GEN-LAST:event_addBtnMouseClicked

    private void deleteBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteBtnMouseClicked
        if(id != 0){
            int choix = JOptionPane.showConfirmDialog(this, "Vous étes sur?");
            if(choix == 0){
                if(us.delete(us.findById(id))){
                    nomTxt.setText("");
                    prenomTxt.setText("");
                    loginTxt.setText("");
                    emailTxt.setText("");
                    mdpTxt.setVisible(true);
                    id = 0;
                    load();
                }         
            } 
        }else
            JOptionPane.showMessageDialog(this, "Veuillez choisir un utilisateur.");
    }//GEN-LAST:event_deleteBtnMouseClicked

    private void listUsersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listUsersMouseClicked
        id = Integer.parseInt(model.getValueAt(listUsers.getSelectedRow(), 0).toString());
        nomTxt.setText(model.getValueAt(listUsers.getSelectedRow(), 1).toString());
        prenomTxt.setText(model.getValueAt(listUsers.getSelectedRow(), 2).toString());
        loginTxt.setText(model.getValueAt(listUsers.getSelectedRow(), 3).toString());
        emailTxt.setText(model.getValueAt(listUsers.getSelectedRow(), 4).toString());
        mdpTxt.setVisible(false);
    }//GEN-LAST:event_listUsersMouseClicked

    private void updateBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateBtnMouseClicked
        if(id != 0){
            int choix = JOptionPane.showConfirmDialog(this, "Vous étes sur?");
            String nom = nomTxt.getText();
            String prenom = prenomTxt.getText();
            String loginT = loginTxt.getText();
            String email = emailTxt.getText();
            User user = us.findById(id);
            user.setNom(nom);
            user.setPrenom(prenom);
            user.setLogin(loginT);
            user.setEmail(email);
            if(choix == 0){
                if(us.update(user)){
                    nomTxt.setText("");
                    prenomTxt.setText("");
                    loginTxt.setText("");
                    emailTxt.setText("");
                    mdpTxt.setVisible(true);
                    id = 0;
                    load();
                }         
            } 
        }else
            JOptionPane.showMessageDialog(this, "Veuillez choisir un utilisateur.");
    }//GEN-LAST:event_updateBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionUsers(nom, prenom).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addBtn;
    private javax.swing.JLabel deleteBtn;
    private javax.swing.JTextField emailTxt;
    private javax.swing.JLabel exitBtn;
    private javax.swing.JLabel homeBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTable listUsers;
    private javax.swing.JTextField loginTxt;
    private javax.swing.JPasswordField mdpTxt;
    private javax.swing.JLabel nameLab;
    private javax.swing.JTextField nomTxt;
    private javax.swing.JTextField prenomTxt;
    private javax.swing.JLabel updateBtn;
    // End of variables declaration//GEN-END:variables

    
}
