/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation.gestion;

import entities.GPSTracker;
import entities.Vehicule;
import entities.VehiculeGPSTracker;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import presentation.Main;
import service.GPSTrackerService;
import service.UserService;
import service.VehiculeGPSTrackerService;
import service.VehiculeService;

/**
 *
 * @author HP
 */
public class GestionAffectations extends javax.swing.JFrame {
    private VehiculeGPSTrackerService vgs;
    private VehiculeService vs;
    private GPSTrackerService gs;
    private DefaultTableModel model;
    private static String id;
    private static String nom;
    private static String prenom;
    
    /**
     * Creates new form GestionAffectations
     */
    public GestionAffectations(String nom, String prenom) {
        initComponents();
        this.nom = nom;
        this.prenom = prenom;
        this.setLocationRelativeTo(null);
        vgs = new VehiculeGPSTrackerService();
        vs = new VehiculeService();
        gs = new GPSTrackerService();
        model = (DefaultTableModel) listAffectations.getModel();
        nameLab.setText(nom + " " + prenom);
        load();
        loadTrackers();
        loadVehicules();  
    }
    
    private void load(){
        model.setRowCount(0);
        for(VehiculeGPSTracker vg : vgs.findAll()){
            
            if(vg.getDateFin() == null)
               model.addRow(new Object []{
                vg.getId(),
                vg.getGpsTracker().getSimNumber(),
                vg.getVehicule().getMatricule(),               
                vg.getDateDebut(),
                "Affecté"
            }); 
            
            else
                model.addRow(new Object []{
                vg.getId(),
                vg.getGpsTracker().getSimNumber(),
                vg.getVehicule().getMatricule(),               
                vg.getDateDebut(),
                vg.getDateFin()
            }); 
               
        }
    }
    
    private void loadTrackers(){
        trackerTxt.removeAllItems();
        for(GPSTracker g : vgs.findTrackersNotNull())
            trackerTxt.addItem(g.getSimNumber());      
    }
    
    private void loadVehicules(){
        vehiculeTxt.removeAllItems();
        for(Vehicule v : vgs.findVehicules())
            vehiculeTxt.addItem(v.getMatricule());      
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        exitBtn = new javax.swing.JLabel();
        homeBtn = new javax.swing.JLabel();
        nameLab = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listAffectations = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        vehiculeTxt = new javax.swing.JComboBox();
        trackerTxt = new javax.swing.JComboBox();
        dateTxt = new com.toedter.calendar.JDateChooser();
        jPanel5 = new javax.swing.JPanel();
        affecterBtn = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        desaffecterBtn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(32, 33, 35));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(51, 102, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(51, 102, 255));
        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 0, 1, 40));

        exitBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentation/images/close.png"))); // NOI18N
        exitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitBtnMouseClicked(evt);
            }
        });
        jPanel3.add(exitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 0, -1, -1));

        homeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentation/images/home.png"))); // NOI18N
        homeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeBtnMouseClicked(evt);
            }
        });
        jPanel3.add(homeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 0, -1, -1));

        nameLab.setFont(new java.awt.Font("Cascadia Mono", 0, 14)); // NOI18N
        jPanel3.add(nameLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 25, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 70));

        jPanel2.setBackground(new java.awt.Color(51, 102, 255));
        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(411, 70, 1, 570));

        jLabel1.setFont(new java.awt.Font("Cascadia Mono", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 102, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Liste des affectations");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, 550, -1));

        jLabel2.setFont(new java.awt.Font("Cascadia Mono", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 102, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Formumaire de gestion");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 410, -1));

        listAffectations.setFont(new java.awt.Font("Cascadia Mono", 0, 12)); // NOI18N
        listAffectations.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Tracker", "Véhicule", "Date début", "Date fin"
            }
        ));
        listAffectations.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listAffectationsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listAffectations);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, 510, 480));

        jLabel3.setFont(new java.awt.Font("Cascadia Mono", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 102, 255));
        jLabel3.setText("Tracker :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 290, -1));

        jLabel4.setFont(new java.awt.Font("Cascadia Mono", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 102, 255));
        jLabel4.setText("Véhicule :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 290, -1));

        jLabel5.setFont(new java.awt.Font("Cascadia Mono", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 102, 255));
        jLabel5.setText("Date début :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 290, -1));

        vehiculeTxt.setBackground(new java.awt.Color(32, 33, 35));
        vehiculeTxt.setFont(new java.awt.Font("Cascadia Mono", 0, 12)); // NOI18N
        jPanel1.add(vehiculeTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 275, 300, 40));

        trackerTxt.setBackground(new java.awt.Color(32, 33, 35));
        trackerTxt.setFont(new java.awt.Font("Cascadia Mono", 0, 12)); // NOI18N
        jPanel1.add(trackerTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 175, 300, 40));
        jPanel1.add(dateTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 290, 35));

        jPanel5.setBackground(new java.awt.Color(32, 33, 35));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 255)));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        affecterBtn.setFont(new java.awt.Font("Cascadia Mono", 0, 18)); // NOI18N
        affecterBtn.setForeground(new java.awt.Color(51, 102, 255));
        affecterBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        affecterBtn.setText("AFFECTER");
        affecterBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        affecterBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                affecterBtnMouseClicked(evt);
            }
        });
        jPanel5.add(affecterBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 0, 290, 45));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 480, 290, 45));

        jPanel6.setBackground(new java.awt.Color(32, 33, 35));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 255)));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        desaffecterBtn.setFont(new java.awt.Font("Cascadia Mono", 0, 18)); // NOI18N
        desaffecterBtn.setForeground(new java.awt.Color(51, 102, 255));
        desaffecterBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        desaffecterBtn.setText("DESAFFECTER");
        desaffecterBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        desaffecterBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                desaffecterBtnMouseClicked(evt);
            }
        });
        jPanel6.add(desaffecterBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 45));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 550, 290, 45));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitBtnMouseClicked

    private void homeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeBtnMouseClicked
        this.setVisible(false);
        (new Main(nom, prenom)).setVisible(true);
    }//GEN-LAST:event_homeBtnMouseClicked

    private void listAffectationsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listAffectationsMouseClicked
        id = model.getValueAt(listAffectations.getSelectedRow(), 0).toString();
        VehiculeGPSTracker vg = vgs.findById(Integer.parseInt(id));
        if(vg.getDateFin() != null)
            JOptionPane.showMessageDialog(this, "Impossible de désaffecter ce tracker.");
    }//GEN-LAST:event_listAffectationsMouseClicked

    private void affecterBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_affecterBtnMouseClicked
        Vehicule vehicule = vs.findByMatricule(vehiculeTxt.getSelectedItem().toString());
        GPSTracker tracker = gs.findBySimNumber(trackerTxt.getSelectedItem().toString()) ;
        Date date = dateTxt.getDate();
        if(!date.equals("")){
            if(vgs.create(new VehiculeGPSTracker(date, null, vehicule, tracker))){
                load();
                loadTrackers();
                loadVehicules();  
            }
        }else
            JOptionPane.showMessageDialog(this, "Tous les champs sont obligatoires.");
    }//GEN-LAST:event_affecterBtnMouseClicked

    private void desaffecterBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_desaffecterBtnMouseClicked
        if(id != null){           
            int choix = JOptionPane.showConfirmDialog(this, "Vous étes sur?");
            VehiculeGPSTracker vg = vgs.findById(Integer.parseInt(id));
            vg.setDateFin(new Date());
            if(choix == 0){
                if(vgs.updateDateFin(vg)){
                    id = null;
                    load();
                    loadTrackers();
                    loadVehicules();  
                }
            }
        }else
            JOptionPane.showMessageDialog(this, "Veuillez choisir un ligne.");
    }//GEN-LAST:event_desaffecterBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionAffectations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionAffectations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionAffectations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionAffectations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionAffectations(nom, prenom).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel affecterBtn;
    private com.toedter.calendar.JDateChooser dateTxt;
    private javax.swing.JLabel desaffecterBtn;
    private javax.swing.JLabel exitBtn;
    private javax.swing.JLabel homeBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable listAffectations;
    private javax.swing.JLabel nameLab;
    private javax.swing.JComboBox trackerTxt;
    private javax.swing.JComboBox vehiculeTxt;
    // End of variables declaration//GEN-END:variables
}
